# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

se = Project.create(title: "Social Eats", tag_line: "The best Rails app for creating food events with friends!", description: "Have you ever been new to corporation and been unable to find the great lunch spots? Do your co-workers constantly come back from lunch at restaurants you wish you'd known about?  Social-Eats is here to help!  Social Eats was developed to answer the question: where is everyone going for lunch? Developed as a group project at the Flatiron School, Social Eats is built using Ruby on Rails and the MVC design pattern.  JQuery and Javascript are used for AJAX functionality to provide a seamless user experience.  The Yelp API is used for the event location search function and the Geocoder gem grabs the user's location when one is not provided.  Rails 5 is implement and used with Action Cable and Redis for real-time chat function on events pages.  Relationships are designed with Active Record and we are using a Postgresql database.", url: "https://social-eats.herokuapp.com", photo: "http://i.imgur.com/x242xO1.png")
fs = Project.create(title: "Flip/Side", tag_line: "The most helpful decision making Rails app!", description: "How do you make decisions? Do you have endless scraps of paper with pros and cons lists?  Enter Flip/Side!  Flip/Side is designed to make the decision-making process easier for users. Users can make new issues, public or private, and assign pros and cons to each issue. Users also assign weights to the pros and cons. The app then offers a suggestion of whether or not the issue looks positive (you should do it) or negative (you probably shouldn't do it).  The application was developed using Ruby on Rails and the MVC design pattern and uses a custom decorator to wrap view logic.  JQuery and JavaScript are utilized for AJAX functionality and a seamless user experience.  BCrypt gem provides custom user authentication and security.  Test framework built with RSPEC, Capybara, and Selenium.  Designed relationships with Active Record and used a Postgresql database.", url: "https://flip-side.herokuapp.com", photo: "http://i.imgur.com/hTqBEan.png")
e = Project.create(title: "Elevate", tag_line: "A beautiful goal-tracking Ember App with custom Rails API!", description: "What is the best way to achieve your goals? Track them!  Elevate is here to help you keep track of your goals and the action items to complete those goals.  Elevate was built with customer Rails API backend, using the rails-api gem, Active Model Serializers, and the JSON API Adapter.  JWT Ruby gem for custom JWT authorization and security; customer authorization flow on client side application using Ember Simple Auth and JWT.  Ember.js frontend designed with Bootstrap and custom CSS.  Wrote custom functions to randomize background image and quotes upon page refresh.  Utilized Ember.js for seamless user experience and application page transitions.", url: "https://elevate-life.herokuapp.com", photo: "http://i.imgur.com/votR64N.png")
